spring:
  application:
    name: redis
  datasource:
    url: jdbc:h2:mem:redis
    driver-class-name: org.h2.Driver
    username: redis
    password: redis1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      topics: testTopic

---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      port: 6379
